### ISSUE TITLE
crnn识别里的char_file文件夹是什么

### ISSUE THREAD

**Issue by GUWjj** [felixBrave/ocr_chinese#14]
作者你好，我想请问crnn里network中的char_file的txt文件是什么？

**Comment by GUWjj** [comment]
> 作者你好，我想请问crnn里network中的char_file的txt文件是什么？

**Comment by felixBrave** [comment]
@GUWjj 可以理解为文字标签，crnn预测输出一个数值，然后拿着这个数值去char_file中查找；
