### ISSUE TITLE
您好，我的输出结果不对，帮忙解决下

### ISSUE THREAD

**Issue by a-ltj** [felixBrave/ocr_chinese#20]
跑测试east没报错，但结果一直是quad invalid with vertex num less then 4.

**Comment by Cornflowerzbq** [comment]
> 跑测试east没报错，但结果一直是quad invalid with vertex num less then 4.

您好，我也是这个问题，请问当时解决了吗

**Comment by fsddj** [comment]
> > 跑测试east没报错，但结果一直是quad invalid with vertex num less then 4.
> 
> 您好，我也是这个问题，请问当时解决了吗
 您好，我也是这个问题，请问解决了吗

**Comment by Cornflowerzbq** [comment]
> > > 跑测试east没报错，但结果一直是quad invalid with vertex num less then 4.
> > 
> > 
> > 您好，我也是这个问题，请问当时解决了吗
> > 您好，我也是这个问题，请问解决了吗

还没有 是这个用不了了吗
