### ISSUE TITLE
使用了预训练的参数但是shape是不是有点问题

### ISSUE THREAD

**Issue by JulianGuSM** [felixBrave/ocr_chinese#6]
我是报这个错误
`ValueError: Dimension 1 in both shapes must be equal, but are 5994 and 5990. Shapes are [512,5994] and [512,5990]. for 'Assign_110' (op: 'Assign') with input shapes: [512,5994], [512,59
90]`

**Comment by snialsss** [comment]
哥们解决的了没不知道怎么修改

**Comment by 15026529688** [comment]
同问  这个问题是什么意思

**Comment by SoftCharacter** [comment]
兄弟解决了吗
