### ISSUE TITLE
A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of 6d6bbae143d832006294945121d1f1fc so we will re-download the data. Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5

### ISSUE THREAD

**Issue by WestbrookZero** [felixBrave/ocr_chinese#8]
运行predict.py，提示这个，然后运行一段时间就不动了，
A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of 6d6bbae143d832006294945121d1f1fc so we will re-download the data.
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5

27975680/58889256 [=============>................] - ETA: 22:29
27992064/58889256 [=============>................] - ETA: 22:28
28016640/58889256 [=============>................] - ETA: 22:26
28033024/58889256 [=============>................] - ETA: 22:25
28049408/58889256 [=============>................] - ETA: 22:24
28065792/58889256 [=============>................] - ETA: 22:24
28082176/58889256 [=============>................] - ETA: 22:23
28098560/58889256 [=============>................] - ETA: 22:22
28114944/58889256 [=============>................] - ETA: 22:21
28131328/58889256 [=============>................] - ETA: 22:20
28155904/58889256 [=============>................] - ETA: 22:18
28172288/58889256 [=============>................] - ETA: 22:17
28188672/58889256 [=============>................] - ETA: 22:16
28205056/58889256 [=============>................] - ETA: 22:15
28221440/58889256 [=============>................] - ETA: 22:14
28237824/58889256 [=============>................] - ETA: 22:13
28254208/58889256 [=============>................] - ETA: 22:12
28270592/58889256 [=============>................] - ETA: 22:11

**Comment by felixBrave** [comment]
@WestbrookZero 网络问题没有下载完整，删除原来的文件，百度网盘https://pan.baidu.com/s/1JR1ogv0unjrfLquBDqHh6g，提取码en9i

**Comment by WestbrookZero** [comment]
解决了，谢谢！

**Comment by Vickywhy** [comment]
> 解决了，谢谢！

请问这个文件放在哪个位置啊
